### ISSUE TITLE
interpret-only/xml_structure/arg_attrib.out

### ISSUE THREAD

**Issue by xReav3r** [jk8/ipp-2020-tests#9]
"Interpret navíc oproti sekci 3.1 podporuje
existenci volitelných dokumentačních textových atributů name a description v kořenovém elementu
program."

Atribut "typ" není v argumentu povolen.

Další chyba se nachází v:
interpret-only/xml_structure/instruction_attrib.src
Zadání říká, že name je podporován v elementu "program", ne v argumentu.

**Comment by jk8** [comment]
Dík za připomínku.

Je to však zaměr. Původně zmíněné testy očekávali chybu při nadbytečném atributu. Později jsme došli k závěru, že nadbytečný atribut v libovolném elementu není chyba (na Discordu je dohledatelná odpověď od dr. Křivky na toto téma). Proto jsme tyto testy upravili, tak aby očekávaly bezchybný výstup interpretu.
